services:
  scraper:
    build: .
    volumes:
      - .:/app # Map the current directory to /app inside the container
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: poetry run python src/migros_scraper.py

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    tmpfs:
      - /data/db

  test:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - PYTHONPATH=/app
    command: poetry run pytest
