# -*- coding: utf-8 -*-
"""RegEx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Gmh1azlhiV-sKaPxuXdR-r8oRgCUmgC
"""

import re

whatIsRegEx = "A regular expression (or RE) specifies a set of strings that matches it; the functions in this module let you check if a particular string matches a given regular expression (or if a given regular expression matches a particular string, which comes down to the same thing)."


matche = re.search('matche..',whatIsRegEx)
if matche is not None:
  print(matche)
  print(matche.group(0))

"""Finden folgende Gruppen (siehe https://docs.python.org/2/library/re.html für RegExp in python)


*   expression
*   module
*   func



"""

# TODO: put here your code

"""Man kann RegEx auch für das Parsen/Einlesen von strukturierten Daten."""

htmlCode = "<html><body><H1> Hello World! </H1> <p>Just checking if somebody is there... </p></body></html>"
import IPython
IPython.display.HTML(htmlCode)

"""Lesen wir den Inhalt der Hauptzeile aus.

"""

re.search("<H1>.*</H1>", htmlCode).group(0)[4:-5]

"""Extrahiere bitte die Emails von folgenden String"""

textEmails = '@geoffreyhinton purple alice@google.com, blah monkey bob@abc.com blah dishwasher '
# TODO use regexp to extract from textEmails the emails put in the list emailsExtracted

"""Check for multiple matches (greedy vs non greedy)

"""



"""Versuchen wir jetzt längere Texte zu verarbeiten."""

import nltk
nltk.download('gutenberg')

emma = nltk.corpus.gutenberg.words('austen-emma.txt')

"""emma ist kein String an sich, es ist ein array aus Strings (siehe type(emma)). https://www.nltk.org/api/nltk.corpus.reader.html#nltk.corpus.reader.util.StreamBackedCorpusView

Siehe: https://www.geeksforgeeks.org/python-convert-list-characters-string/?ref=lbp oder https://stackoverflow.com/questions/21948019/python-untokenize-a-sentence

Finde wo das Wort "horse" auftaucht, und gib bitte den Kontext und Position an:
"""



"""Now, let's dive in real world needs:"""

import requests
mensaPlan = requests.get("https://fhnw.sv-restaurant.ch/de/menuplan/")

day_names = ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag']
import datetime
day_name = day_names[datetime.datetime.today().weekday()]
content=str(mensaPlan.content)[2:-1]
print(content)

"""Finde was es heute zur Essensauswahl gibt"""

# Parse html with relevant regexp

"""Erweiterte Aufgabe: gib aus, was es diese Woche zur Auswahl gibt!"""

