name: Add IP to MongoDB Atlas

on:
  workflow_call:
    inputs:
      MONGO_API_PUBLIC_KEY:
        required: true
        type: string
      MONGO_API_PRIVATE_KEY:
        required: true
        type: string
      PROJECT_ID:
        required: true
        type: string

jobs:
  add-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get public IP address
        run: |
          IP=$(curl https://ipinfo.io/ip)
          echo "PUBLIC_IP=$IP" >> $GITHUB_ENV

      - name: Add GitHub runner IP to MongoDB Atlas
        run: |
          DATA=$(jq -n --arg ip "$PUBLIC_IP" --arg comment "My GitHub Action IP" \
            '{ipAddress: $ip, comment: $comment}')
          echo "Sending this JSON payload: $DATA"
          curl -u "${{ inputs.MONGO_API_PUBLIC_KEY }}:${{ inputs.MONGO_API_PRIVATE_KEY }}" \
              --digest \
              -X POST \
              --header "Content-Type: application/json" \
              --data "$DATA" \
              "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ inputs.PROJECT_ID }}/accessList"
