name: Add IP to MongoDB Atlas
on:
  workflow_call: # This allows this action to be called from another workflow
  workflow_dispatch: # Allow manual runs

jobs:
  add-ip:
    runs-on: ubuntu-latest
    steps:
      # Get the current runner's public IP address
      - name: Get public IP address
        run: |
          IP=$(curl https://ipinfo.io/ip)
          echo "PUBLIC_IP=$IP" >> $GITHUB_ENV

      # Debug: Print the JSON data
      - name: Print the JSON data
        run: |
          DATA="{\"ipAddress\": \"$PUBLIC_IP\", \"comment\": \"My GitHub Action IP\"}"
          echo "JSON Payload: $DATA"

      # Add the IP address to MongoDB Atlas via the API
      - name: Add GitHub runner IP to MongoDB Atlas
        run: |
          DATA="{\"ipAddress\": \"$PUBLIC_IP\", \"comment\": \"My GitHub Action IP\"}"
          echo "Sending this JSON payload: $DATA"
          curl -u "${{ secrets.MONGO_API_PUBLIC_KEY }}:${{ secrets.MONGO_API_PRIVATE_KEY }}" \
              --digest \
              -X POST \
              --header "Content-Type: application/json" \
              --data "$DATA" \
              "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ secrets.PROJECT_ID }}/accessList"
